{{- if and .Values.secrets.create .Values.secrets.ngcApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: vista3d-secrets
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
type: Opaque
data:
  ngc-api-key: {{ .Values.secrets.ngcApiKey | b64enc | quote }}
{{- end }}

