{{- if .Values.imageServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vista3d.imageServer.deploymentName" . }}
  labels:
    {{- include "vista3d.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-server
spec:
  replicas: {{ .Values.imageServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "vista3d.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: image-server
  template:
    metadata:
      labels:
        {{- include "vista3d.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: image-server
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "vista3d.serviceAccountName" $ }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.imageServer.name }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.imageServer.image.repository }}:{{ .Values.imageServer.image.tag }}"
          imagePullPolicy: {{ .Values.imageServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.imageServer.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.imageServer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- toYaml .Values.imageServer.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.imageServer.resources | nindent 12 }}
      volumes:
        - name: output-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-output-pvc
        - name: dicom-data
          persistentVolumeClaim:
            claimName: {{ include "vista3d.fullname" . }}-dicom-pvc
{{- end }}

